version: '2.1'

services:
  base:
    container_name: base
    user: root
    env_file:
      - .env
    image: base
    build:
      context: base
      args:
        - TZ=Europe/Czech
    entrypoint: /base/entrypoint.sh
    volumes:
      - ./base:/base
      - ./fuel-ui:/fuel-ui
      - ./fuel-web:/fuel-web

  test:
    container_name: test
    image: base
    user: root
    env_file:
      - .env
    volumes:
      - ./test:/test
      - ./fuel-ui:/fuel-ui
      - ./fuel-web:/fuel-web
    entrypoint: /test/entrypoint.sh
    ports:
      - "${NODE_PORT}"
      - "9000"
    depends_on:
      - base
    links:
      - dev-server
      - selenium

  db:
    image: postgres:9.5
    ports:
      - "${NAILGUN_DB_PORT}"
    environment:
      - POSTGRES_PASSWORD=${DB_DB_ROOTPW}
      - POSTGRES_USER=${DB_ROOT}
      - POSTGRES_DATABASE=${NAILGUN_DB}
      - NAILGUN_DB=${NAILGUN_DB}
      - NAILGUN_DB_USER=${NAILGUN_DB_USER}
      - NAILGUN_DB_USERPW=${NAILGUN_DB_USERPW}
    ports:
      - "${NAILGUN_DB_PORT}"

  dev-server:
    container_name: dev-server
    user: root
    env_file:
      - .env
    build:
      context: dev-server
      args:
        - FUEL_WEB_REQS=${FUEL_WEB_REQS}
    volumes:
      - ./dev-server:/dev-server
      - ./fuel-ui:/fuel-ui
      - ./fuel-web:/fuel-web
      - ./dev-server/log:/var/log/nailgun
    entrypoint: /dev-server/entrypoint.sh
    environment:
      - NAILGUN_HOST=${NAILGUN_HOST}
      - REMOTE_HOST=${NAILGUN_HOST}
      - FUEL_WEB_ROOT=${FUEL_WEB_ROOT}
      - ARTIFACTS=${ARTIFACTS}
    ports:
      - "9057"
      - "${NAILGUN_PORT}"
      - "${DEV_SERVER_PORT}"
    depends_on:
      - build
    links:
      - db
      - selenium

  selenium:
    container_name: selenium
    build:
      context: selenium/
      args:
        - GECKODRIVER_VERSION=0.9.0
        - FIREFOX_VERSION=46.0
    env_file:
      - .env
    volumes:
      - ./selenium:/selenium
    user: seluser
    entrypoint: /selenium/entrypoint.sh
    ports:
      - "${SELENIUM_SERVER_PORT}"
